<?php

namespace App\Constants;

class KeyWordHelper
{
    public const SPECIALTY_HELPER_WORD = [
        // --- Cardiology (أمراض القلب والأوعية الدموية) ---
        'heart' => 'Cardiology',
        'cardio' => 'Cardiology',
        'chest pain' => 'Cardiology',
        'قلب' => 'Cardiology',
        'شرايين' => 'Cardiology',
        'نبض' => 'Cardiology',
        'خفقان' => 'Cardiology',
        'جلطة' => 'Cardiology',
        'ضغط' => 'Cardiology',
        'قسطرة' => 'Cardiology',
        'نهجان' => 'Cardiology',

        // --- Neurology (أمراض المخ والأعصاب) ---
        'brain' => 'Neurology',
        'nerve' => 'Neurology',
        'stroke' => 'Neurology',
        'headache' => 'Neurology',
        'عصب' => 'Neurology',
        'مخ' => 'Neurology',
        'أعصاب' => 'Neurology',
        'صداع' => 'Neurology',
        'شلل' => 'Neurology',
        'تنميل' => 'Neurology',
        'صرع' => 'Neurology',
        'تشنج' => 'Neurology',
        'نسيان' => 'Neurology',
        'دوخة' => 'Neurology',

        // --- Orthopedics (جراحة العظام والمفاصل) ---
        'bone' => 'Orthopedics',
        'joint' => 'Orthopedics',
        'fracture' => 'Orthopedics',
        'back pain' => 'Orthopedics',
        'عظام' => 'Orthopedics',
        'مفاصل' => 'Orthopedics',
        'ظهر' => 'Orthopedics',
        'كسر' => 'Orthopedics',
        'ركبة' => 'Orthopedics',
        'عمود فقري' => 'Orthopedics',
        'غضروف' => 'Orthopedics',
        'رقبة' => 'Orthopedics',
        'خلع' => 'Orthopedics',
        'روماتيزم' => 'Orthopedics',

        // --- Dermatology (الأمراض الجلدية والتناسلية) ---
        'skin' => 'Dermatology',
        'hair' => 'Dermatology',
        'rash' => 'Dermatology',
        'laser' => 'Dermatology',
        'جلد' => 'Dermatology',
        'حساسية' => 'Dermatology',
        'شعر' => 'Dermatology',
        'بشرة' => 'Dermatology',
        'حب شباب' => 'Dermatology',
        'أكزيما' => 'Dermatology',
        'صدفية' => 'Dermatology',
        'حكة' => 'Dermatology',
        'ثعلبة' => 'Dermatology',
        'بقع' => 'Dermatology',

        // --- Ophthalmology (طب وجراحة العيون) ---
        'eye' => 'Ophthalmology',
        'vision' => 'Ophthalmology',
        'glasses' => 'Ophthalmology',
        'lasik' => 'Ophthalmology',
        'عين' => 'Ophthalmology',
        'بصر' => 'Ophthalmology',
        'عيون' => 'Ophthalmology',
        'نظارة' => 'Ophthalmology',
        'قرنية' => 'Ophthalmology',
        'مياه بيضاء' => 'Ophthalmology',
        'مياه زرقاء' => 'Ophthalmology',
        'حول' => 'Ophthalmology',
        'جفاف العين' => 'Ophthalmology',

        // --- ENT - Ear, Nose and Throat (أنف وأذن وحنجرة) ---
        'ear' => 'ENT',
        'nose' => 'ENT',
        'throat' => 'ENT',
        'sinus' => 'ENT',
        'hearing' => 'ENT',
        'أذن' => 'ENT',
        'أنف' => 'ENT',
        'حنجرة' => 'ENT',
        'حلق' => 'ENT',
        'لوز' => 'ENT',
        'جيوب أنفية' => 'ENT',
        'صوت' => 'ENT',
        'دوار' => 'ENT',
        'طنين' => 'ENT',
        'بلع' => 'ENT',

        // --- Pediatrics (طب الأطفال) ---
        'child' => 'Pediatrics',
        'pediatric' => 'Pediatrics',
        'baby' => 'Pediatrics',
        'infant' => 'Pediatrics',
        'طفل' => 'Pediatrics',
        'أطفال' => 'Pediatrics',
        'رضيع' => 'Pediatrics',
        'نمو' => 'Pediatrics',
        'تطعيم' => 'Pediatrics',
        'تبول لاإرادي' => 'Pediatrics',
        'حديث الولادة' => 'Pediatrics',

        // --- Gastroenterology (أمراض الجهاز الهضمي والكبد) ---
        'stomach' => 'Gastroenterology',
        'digestive' => 'Gastroenterology',
        'liver' => 'Gastroenterology',
        'colon' => 'Gastroenterology',
        'بطن' => 'Gastroenterology',
        'هضم' => 'Gastroenterology',
        'كبد' => 'Gastroenterology',
        'قولون' => 'Gastroenterology',
        'معدة' => 'Gastroenterology',
        'حموضة' => 'Gastroenterology',
        'ارتجاع' => 'Gastroenterology',
        'إسهال' => 'Gastroenterology',
        'إمساك' => 'Gastroenterology',
        'منظار' => 'Gastroenterology',
        'غازات' => 'Gastroenterology',
        'غثيان' => 'Gastroenterology',

        // --- Nephrology & Urology (أمراض الكلى والمسالك البولية) ---
        'kidney' => 'Nephrology',
        'urinary' => 'Urology',
        'prostate' => 'Urology',
        'stone' => 'Urology',
        'بول' => 'Urology',
        'مسالك' => 'Urology',
        'كلية' => 'Nephrology',
        'كلى' => 'Nephrology',
        'بروستاتا' => 'Urology',
        'حصوة' => 'Urology',
        'حصوات' => 'Urology',
        'مثانة' => 'Urology',
        'غسيل كلى' => 'Nephrology',

        // --- Psychiatry (الطب النفسي وعلاج الإدمان) ---
        'mental' => 'Psychiatry',
        'psychiatry' => 'Psychiatry',
        'depression' => 'Psychiatry',
        'anxiety' => 'Psychiatry',
        'نفسي' => 'Psychiatry',
        'اكتئاب' => 'Psychiatry',
        'قلق' => 'Psychiatry',
        'توتر' => 'Psychiatry',
        'وسواس' => 'Psychiatry',
        'إدمان' => 'Psychiatry',
        'خوف' => 'Psychiatry',
        'نوم' => 'Psychiatry',
        'أرق' => 'Psychiatry',

        // --- Gynecology & Obstetrics (أمراض النساء والتوليد) ---
        'woman' => 'Gynecology',
        'pregnancy' => 'Gynecology',
        'obgyn' => 'Gynecology',
        'period' => 'Gynecology',
        'نساء' => 'Gynecology',
        'ولادة' => 'Gynecology',
        'حمل' => 'Gynecology',
        'عقم' => 'Gynecology',
        'دورة' => 'Gynecology',
        'مبايض' => 'Gynecology',
        'رحم' => 'Gynecology',
        'إجهاض' => 'Gynecology',
        'سونار' => 'Gynecology',

        // --- Oncology (أورام وسرطان) ---
        'cancer' => 'Oncology',
        'tumor' => 'Oncology',
        'chemo' => 'Oncology',
        'سرطان' => 'Oncology',
        'ورم' => 'Oncology',
        'أورام' => 'Oncology',
        'كيماوي' => 'Oncology',
        'إشعاعي' => 'Oncology',
        'خزعة' => 'Oncology',

        // --- Dentistry (طب وجراحة الأسنان) ---
        'tooth' => 'Dentistry',
        'dental' => 'Dentistry',
        'gum' => 'Dentistry',
        'أسنان' => 'Dentistry',
        'ضرس' => 'Dentistry',
        'لثة' => 'Dentistry',
        'تقويم' => 'Dentistry',
        'حشو' => 'Dentistry',
        'خلع أسنان' => 'Dentistry',
        'زراعة أسنان' => 'Dentistry',

        // --- Endocrinology (الغدد الصماء والسكري) ---
        'diabetes' => 'Endocrinology',
        'thyroid' => 'Endocrinology',
        'hormone' => 'Endocrinology',
        'سكر' => 'Endocrinology',
        'غدة' => 'Endocrinology',
        'غدد' => 'Endocrinology',
        'هرمونات' => 'Endocrinology',
        'انسولين' => 'Endocrinology',
        'نمو' => 'Endocrinology',
        'سمنة' => 'Endocrinology',

        // --- Pulmonology (الأمراض الصدرية والجهاز التنفسي) ---
        'lung' => 'Pulmonology',
        'respiratory' => 'Pulmonology',
        'cough' => 'Pulmonology',
        'asthma' => 'Pulmonology',
        'صدر' => 'Pulmonology',
        'رئة' => 'Pulmonology',
        'تنفس' => 'Pulmonology',
        'كحة' => 'Pulmonology',
        'ربو' => 'Pulmonology',
        'حساسية صدر' => 'Pulmonology',
        'بلغم' => 'Pulmonology',
        'ضيق تنفس' => 'Pulmonology',

        // --- Hematology (أمراض الدم) ---
        'blood' => 'Hematology',
        'anemia' => 'Hematology',
        'دم' => 'Hematology',
        'أنيميا' => 'Hematology',
        'فقر دم' => 'Hematology',
        'سيولة' => 'Hematology',
        'تجلط' => 'Hematology',
        'صفائح' => 'Hematology'
    ];
}
